### ISSUE TITLE
HIDPI support

### ISSUE THREAD

**Issue by iurienistor** [iurie-sw/redkite#13]
HIDPI support.

**Comment by TatriX** [comment]
Could you please elaborate on why it's marked as `wontdo`?

**Comment by iurienistor** [comment]
I don't mean this feature wouldn't be nice to be but I'll say something unpopular :)
Even if a System Level / GUI toolkit level makes this possible, anyway the application that uses images and bitmap icons needs to create a set of all these images for every scale factor... at least two sets. Because, otherwise the icons and images will depixelated when scaling. - https://www.eizo.com/library/basics/hidpi/

Second I believe this is a transition to a new standard regarding the resolution, and the current situation is a kind of a "mess". Thus, let's the application develop this scaling if there is necessity, or wait when this transition will end and just make a UI design taking in consideration new resolution standard (and not need for any scalling). - https://blog.elementary.io/what-is-hidpi/

Due to these reasons for now I have no plans to implemented this, and probably there will not be needed soon. But if someone finds Redkite useful and wants to contribute, I am open :)

**Comment by hfiguiere** [comment]
Having filed iurie-sw/geonkick#80, the problem is that without proper implementation the UI is simply unusable on a HiDPI display because everything is too small (as it ignore the scale factor and draw everything as 1 pixel on screen is one pixel in UI). And the hardware I run is a 3 year old laptop.

If it was pixelated (ie zoomed) it would be functional at least.

**Comment by iurienistor** [comment]
Ok, I'll try to see what I can do in the next release (for Geonkick 3.0).

**Comment by iurienistor** [comment]
I think I have implemented the scaling. Try to build Geonkick from the branch feat/hdpi with Redkite from the branch feat/hidpi. Everything is a little blurred and the scale factor is 2 for now.  To scale the window press left ctrl + f. In the future I'll improve things regarding blurring (because labels an buttons are images). Also, I need to save this settings when hdpi is enabled.
On my PC moving envelope points is slow due to encreased are of the drawing (x2), but my PC is quite old. The envelope also is burred but this will be fixed in the future.

**Comment by iurienistor** [comment]
I have implemented this. The user needs manually to called methods passing the scaling.

Scaling will make the UI to be blurred. In the future I'll improve things in Redkite even probably make this automatic HiDPI detection.
