### ISSUE TITLE
Missing manpage for rkpng2c

### ISSUE THREAD

**Issue by eeickmeyer** [iurie-sw/redkite#23]
Hi! I'm packaging redkite for inclusion in Ubuntu!

The only issue I'm running into is that rkpng2c has no manpage, which is pretty much a requirement for any tool in /usr/bin or /bin. Is there any way you can write one?

Thanks!

**Comment by iurienistor** [comment]
Hi! Thank you for packaging redkite. Yes, I'll create a manpage for rkpng2c. It will be soon published in the version 1.0.
