### ISSUE TITLE
Please unify your license

### ISSUE THREAD

**Issue by magnetophon** [iurie-sw/redkite#25]
The [readme says GPL 3](https://github.com/iurie-sw/redkite#description) but [the source code says GPL3+](https://gitlab.com/iurie-sw/redkite/-/blob/7e15627dfd54c748129fe1cff9a4f83f034b1d9a/src/RkContainer.cpp#L9-11).

Which is it?  ;)

PS: Thanks for keeping the releases up to date!

**Comment by iurienistor** [comment]
Every code file starts with: 
GeonKick is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.

**"either version 3 of the License, or
 * (at your option) any later version."**

But ok, I'll update README, in the later releases. Thank you!

**Comment by magnetophon** [comment]
Sorry to put you trough this!

Would you mind doing the same for https://github.com/iurie-sw/geonkick?
The LICENCE file says gpl3 and the source gpl3+.

**Comment by iurienistor** [comment]
> Sorry to put you trough this!
> 
> Would you mind doing the same for https://github.com/iurie-sw/geonkick?
> The LICENCE file says gpl3 and the source gpl3+.

LICENCE file is the copy of the license, there is no such license as GPLv3+, there only GPLv3. The code files on the other hand mentions that the code is released under GPLv3 or automatically above (if there will be released an updated version of GPL license).

**Comment by magnetophon** [comment]
Thanks for clarifying.
